### ISSUE TITLE
Implement Backend for Storing LinktaFlow object into DB

### ISSUE THREAD

**Issue by zhiyi15** [Linkta-org/core#205] opened 2024-06-13 19:44 UTC
**Related Epic**
#120 

**Acceptance Criteria**
- Refactor LinktaFlowController based on latest API design doc
- Integrate LinktaFlowController into genAIController
- Remove unused LLM related files

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by relandboyle** [comment] 2024-06-22 17:25
Duplicate of #233

**Closed by relandboyle** 2024-06-22 17:25 UTC
